# Virtual Environment Setup

In [ ]:
# Install virtualenv to create a virtual environment
!pip install virtualenv

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 28.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 21.6 MB/s eta 0:00:00


In [ ]:
# Create a virtual environment called pytorch_env
!virtualenv pytorch_env

created virtual environment CPython3.10.12.final.0-64 in 1125ms
  creator CPython3Posix(dest=/content/pytorch_env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==24.3.1, setuptools==75.6.0, wheel==0.45.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


In [ ]:
# Activate Virtual Environemnt
!source pytorch_env/bin/activate

# Installing PyTorch in the virutal environemnt

In [ ]:
!pip install torch torchvision torchaudio

# Code Examples from Chapter 12 of the Book

In [ ]:
# Example: Post-Training Quantization in PyTorch

import torch
import torch.quantization
from torchvision import models


# Load a pre-trained model
model = models.resnet18(pretrained=True)
model.eval()


# Fuse the model layers (required before quantization)
model.fuse_model()


# Apply post-training static quantization
model.qconfig = torch.quantization.get_default_qconfig('fbgemm')
torch.quantization.prepare(model, inplace=True)
torch.quantization.convert(model, inplace=True)


# Now the model is quantized and ready for deployment


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
# Example: Applying Unstructured Pruning in PyTorch

import torch
import torch.nn.utils.prune as prune
from torchvision import models


# Load a pre-trained model
model = models.resnet18(pretrained=True)


# Apply global unstructured pruning to all Conv2d layers
for module in model.modules():
    if isinstance(module, torch.nn.Conv2d):
        prune.global_unstructured(
            module, name="weight", amount=0.2
        )


# Remove the pruning reparameterization to make the model ready for deployment
for module in model.modules():
    if isinstance(module, torch.nn.Conv2d):
        prune.remove(module, 'weight')
# The pruned model is now ready for deployment


tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
tensor([[9., 9.],
        [9., 9.]])
