# Virtual Environment Setup

In [1]:
# Install virtualenv to create a virtual environment
!pip install virtualenv

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 53.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 20.6 MB/s eta 0:00:00


In [2]:
# Create a virtual environment called pytorch_env
!virtualenv pytorch_env

created virtual environment CPython3.10.12.final.0-64 in 1280ms
  creator CPython3Posix(dest=/content/pytorch_env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==24.3.1, setuptools==75.6.0, wheel==0.45.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


In [3]:
# Activate Virtual Environemnt
!source pytorch_env/bin/activate

# Installing PyTorch in the virutal environemnt

In [4]:
!pip install torch torchvision torchaudio

# Code Examples from Chapter 2 of the Book

In [5]:
# PyTorch tensor example

import torch

# A scalar (0D tensor)
scalar = torch.tensor(5)
print("A scalar (0D tensor): ", scalar)

# A vector (1D tensor)
vector = torch.tensor([1, 2, 3, 4])
print("A vector (1D tensor): ", vector)

# A matrix (2D tensor)
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("A matrix (2D tensor): ", matrix)

A scalar (0D tensor):  tensor(5)
A vector (1D tensor):  tensor([1, 2, 3, 4])
A matrix (2D tensor):  tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
# Foundation of complex architecture example

# A simple tensor operation: Element-wise addition
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
result = tensor_a + tensor_b
print(result)  # Outputs: tensor([5, 7, 9])


tensor([5, 7, 9])


In [7]:
# 0-dimensional tensor: Scalar

scalar = torch.tensor(7)
print(f"Scalar tensor: {scalar}, Dimension: {scalar.dim()}")

Scalar tensor: 7, Dimension: 0


In [8]:
# 1-dimensional tensor: Vector

vector = torch.tensor([1, 2, 3, 4])
print(f"Vector tensor: {vector}, Dimension: {vector.dim()}")

Vector tensor: tensor([1, 2, 3, 4]), Dimension: 1


In [9]:
# 2-dimensional tensor: Matrix
matrix = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(f"Matrix tensor: {matrix}, Dimension: {matrix.dim()}")

Matrix tensor: tensor([[1, 2],
        [3, 4],
        [5, 6]]), Dimension: 2


In [10]:
# N-dimensional tensor: Higher-dimensional entities
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D tensor: {tensor_3d}, Dimension: {tensor_3d.dim()}")

3D tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]), Dimension: 3


In [14]:
# Superpower of PyTorch tensors over NumPy arrays

# Moving a tensor to GPU (if available)
if torch.cuda.is_available():
    tensor_on_gpu = tensor_3d.cuda()
    print("Tensor moved to GPU:", tensor_on_gpu.device)
else:
    print("GPU not available.")

Tensor moved to GPU: cuda:0


In [13]:
# Broadcasting in PyTorch

a = torch.tensor([1, 2, 3])       # Shape: (3,)
b = torch.tensor([[1], [2], [3]]) # Shape: (3, 1)
result = a + b                    # Result shape: (3, 3)
print("Result: ", result)

Result:  tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])


In [15]:
# Arithmetic Operations: Addition

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.add(a, b)
print(result)  # Outputs: tensor([5, 7, 9])

tensor([5, 7, 9])


In [16]:
# Arithmetic Operations: Substraction

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.sub(a, b)
print(result)  # Outputs: tensor([-3, -3, -3])

tensor([-3, -3, -3])


In [17]:
# Arithmetic Operations: Multiplication

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.mul(a, b)
print(result)  # Outputs: tensor([ 4, 10, 18])

tensor([ 4, 10, 18])


In [18]:
# Arithmetic Operations: Division

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.div(b, a)
print(result)  # Outputs: tensor([4., 2.5, 2.])

tensor([4.0000, 2.5000, 2.0000])


In [19]:
# Matric Operations: Multiplication

A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[2, 0], [1, 3]])
result = torch.matmul(A, B)
print(result)  # Outputs: tensor([[ 4,  6], [10, 12]])

tensor([[ 4,  6],
        [10, 12]])


In [20]:
# Matric Operations: Transpose

matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
transposed = torch.t(matrix)
print(transposed)  # Outputs: tensor([[1, 4], [2, 5], [3, 6]])

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [22]:
# Reshaping Operations: View and Reshape

# Original tensor
tensor = torch.tensor([1, 2, 3, 4, 5, 6])

# Using view
reshaped_view = tensor.view(2, 3)
print("View:", reshaped_view)  # Outputs: tensor([[1, 2, 3], [4, 5, 6]])

# Using reshape
reshaped_reshape = tensor.reshape(2, 3)
print("Reshaped:", reshaped_reshape)  # Outputs: tensor([[1, 2, 3], [4, 5, 6]])

View: tensor([[1, 2, 3],
        [4, 5, 6]])
Reshaped: tensor([[1, 2, 3],
        [4, 5, 6]])


In [23]:
# Reshaping Operations: Squeeze and Unsqueeze

tensor = torch.tensor([[[1, 2, 3]]])
squeezed = tensor.squeeze()
print(squeezed.dim())  # Outputs: 1

1


In [24]:
# The Dynamic Nature of Compute Graphs

# PyTorch
import torch

a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
c = a + b
c.backward() # Gradients are computed here
print(a.grad) # Outputs: 1.0 (because dc/da = 1)


tensor(1.)


In [29]:
# Nodes and Edges in Computational Graphs

x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
z = y * 3

In [30]:
# Autograd and Backpropagation

z.backward()
print(x.grad) # Outputs: 12.0 (because dz/dx = 2*x*3 for x=2)

tensor(12.)


In [31]:
# Detaching from the graph

detached_y = y.detach()
w = detached_y * 3 # w won't be part of the computation graph.

In [32]:
# Create a tensor and enable tracking

x = torch.tensor([2.0, 3.0], requires_grad=True)
print(x.requires_grad)  # Outputs: True

True


In [33]:
# The Computation Graph and `.backward()`

# Compute Gradient
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x * 2
z = y.mean()
z.backward()  # Compute gradients
print(x.grad)  # Outputs: tensor([2., 2.])

tensor([1., 1.])


In [34]:
# Accumulating Gradients

y = x * 2
y.backward(torch.tensor([1.0, 1.0]))  # Using a vector for gradient scaling
print(x.grad)  # Outputs: tensor([2., 2.])

# Doing another operation
y = x * 3
y.backward(torch.tensor([1.0, 1.0]))
print(x.grad)  # Outputs: tensor([5., 5.]) because gradients accumulate


tensor([3., 3.])
tensor([6., 6.])


In [35]:
# Non-Scalar Backward Operations

y = x * 2
# This would raise an error since y is not a scalar:
# y.backward()
# Instead, use:
y.backward(torch.tensor([1.0, 1.0]))


In [36]:
# Disable Gradient Tracking

with torch.no_grad():
    y = x * 2
    print(y.requires_grad)  # Outputs: False


False


In [38]:
# Detach
y = x.detach()
print(y.requires_grad)  # Outputs: False

False


In [39]:
# Creating tensor from list
import torch

tensor_from_list = torch.tensor([1, 2, 3, 4])
print(tensor_from_list)

tensor([1, 2, 3, 4])


In [40]:
# Creating tensor from Numpy array
import numpy as np
import torch

numpy_array = np.array([5, 6, 7, 8])
tensor_from_np = torch.from_numpy(numpy_array)
print(tensor_from_np)


tensor([5, 6, 7, 8])


In [41]:
# Creating tensor with specific data types
import torch

tensor_float = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print(tensor_float)


tensor([1., 2., 3., 4.])


In [42]:
# Creating tensor with zeros and ones
import torch

tensor_zeros = torch.zeros(3, 3)
tensor_ones = torch.ones(3, 3)
tensor_range = torch.arange(0, 10, 2)
print(tensor_zeros, tensor_ones, tensor_range)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) tensor([0, 2, 4, 6, 8])


In [47]:
# Arithemetic operations

x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([5, 6, 7, 8])

sum_tensors = x + y
product_tensors = x * y
print(sum_tensors, product_tensors)


tensor([ 6,  8, 10, 12]) tensor([ 5, 12, 21, 32])


In [48]:
# Matrix operations
import torch

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[5, 6], [7, 8]])

matmul_result = torch.matmul(x, y)
print(matmul_result)


tensor([[19, 22],
        [43, 50]])


In [49]:
# Reshape tensors
import torch

x = torch.arange(10)
reshaped_tensor = x.view(2, 5)
print(reshaped_tensor)

reshaped_tensor_alt = x.reshape(5, 2)
print(reshaped_tensor_alt)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [50]:
# Squeeze & Unsqueeze tensors
import torch

tensor = torch.tensor([[1, 2, 3]])
squeezed_tensor = tensor.squeeze()
print(squeezed_tensor.shape)

unsqueeze_tensor = squeezed_tensor.unsqueeze(dim=0)
print(unsqueeze_tensor.shape)


torch.Size([3])
torch.Size([1, 3])


In [51]:
# Use CUDA

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = x.to(device)
print(x.device)


cuda:0


In [43]:
# Indexing
import torch

x = torch.tensor([0, 1, 2, 3, 4])
print(x[2])


tensor(2)


In [44]:
# Slicing
import torch

print(x[1:4])


tensor([1, 2, 3])


In [45]:
# Concatenating
import torch

y = torch.tensor([5, 6, 7, 8, 9])
concatenated = torch.cat((x, y))
print(concatenated)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [46]:
# Cloning
import torch

y = x.clone()
y[0] = 100
print(x, y)


tensor([0, 1, 2, 3, 4]) tensor([100,   1,   2,   3,   4])
